---
# Allow thymeleaf template changes to reload:
spring.thymeleaf.cache: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: /services
